{
 "title": "Internet SLA monitoring",
 "tags": [
  "speedtest",
  "ping"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Download Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Last Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Last Ping",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds"
    }
   ]
  },
  {
   "title": "Average Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}"
    }
   ]
  },
  {
   "title": "Average Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Average Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds",
     "legendFormat": "ping"
    }
   ]
  },
  {
   "title": "Speedtest Graph",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{}",
     "legendFormat": "Download"
    },
    {
     "expr": "speedtest_upload_bits_per_second{}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 20 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Opened ports",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 20 },
   "targets": [
    { "expr": "python_is_port_open{}", "legendFormat": "{{portNumber}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 27 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "IP history",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 27 },
   "targets": [
    { "expr": "python_host{}", "legendFormat": "{{IP}}" }
   ]
  }
 ]
}